Broker.Web/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Broker.Models;
using Broker.Data;

namespace Broker.Web.Controllers
{
    public class OfferController : BaseController
    {

        // GET: /Offer/
        public ActionResult Index()
        {
            return View(Db.Offers.ToList());
        }

        // GET: /Offer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = Db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // GET: /Offer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Offer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="AmontOfBedrooms,Price,Currency,Address,Area,Client")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                Db.Offers.Add(offer);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: /Offer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = Db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: /Offer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,AmontOfBedrooms,Price,Currency,Address,Area")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(offer).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: /Offer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = Db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: /Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offer offer = Db.Offers.Find(id);
            Db.Offers.Remove(offer);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Broker.Web/Views/Shared/_Layout.cshtml
@using System
@using System.Collections.Generic
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Agencies", "List", "Agency")</li>

                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span>Offers</span>
                                <strong class="caret"></strong>
                            </a>
                            <ul id="dropdownAdmin" class="dropdown-menu userDropdown">
                                <li>
                                    @Html.ActionLink("My Offers", "Index", "Offer", routeValues: null, htmlAttributes: new { title = "User details" })
                                </li>
                                <li>
                                    @Html.ActionLink("Create Offer", "Create", "Offer", routeValues: null, htmlAttributes: new { title = "Manage" })
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span>Search Criterias</span>
                                <strong class="caret"></strong>
                            </a>
                            <ul id="dropdownAdmin" class="dropdown-menu userDropdown">
                                <li>
                                    @Html.ActionLink("My Search Criterias", "Index", "Offer", routeValues: null, htmlAttributes: new { title = "User details" })
                                </li>
                                <li>
                                    @Html.ActionLink("Create Search Criterias", "Create", "Offer", routeValues: null, htmlAttributes: new { title = "Manage" })
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:50px;">
        @if (TempData.ContainsKey("alerts"))
        {
            foreach (var alert in ((List<AlertProps>)TempData["alerts"]))
            {
                <div class="alert @alert.AlertType" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    @Html.Raw(alert.Message)
                </div>
            }
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>